src/Alura.LeilaoOnline.WebApp/Models/Categoria.cs
using System.Collections.Generic;

namespace Alura.LeilaoOnline.WebApp.Models
{
    public class Categoria
    {
        public Categoria()
        {
            Leiloes = new List<Leilao>();
        }

        public int Id { get; set; }
        public string Descricao { get; set; }
        public string Imagem { get; set; }
        public IList<Leilao> Leiloes { get; set; }
    }

    public class CategoriaComInfoLeilao : Categoria
    {
        public int EmRascunho { get; set; }
        public int EmPregao { get; set; }
        public int Finalizados { get; set; }
    }
}

src/Alura.LeilaoOnline.WebApp/Models/SituacaoLeilao.cs
namespace Alura.LeilaoOnline.WebApp.Models
{
    public enum SituacaoLeilao
    {
        Rascunho,
        Pregao,
        Finalizado,
        Arquivado
    }
}

src/Alura.LeilaoOnline.WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using Alura.LeilaoOnline.WebApp.Services;

namespace Alura.LeilaoOnline.WebApp.Controllers
{
    public class HomeController : Controller
    {
        IProdutoService _service;

        public HomeController(IProdutoService service)
        {
            _service = service;
        }

        public IActionResult Index()
        {
            var categorias = _service.ConsultaCategoriasComTotalDeLeiloesEmPregao();
            return View(categorias);
        }

        [Route("[controller]/StatusCode/{statusCode}")]
        public IActionResult StatusCodeError(int statusCode)
        {
            if (statusCode == 404) return View("404");
            return View(statusCode);
        }

        [Route("[controller]/Categoria/{categoria}")]
        public IActionResult Categoria(int categoria)
        {
            var categ = _service.ConsultaCategoriaPorIdComLeiloesEmPregao(categoria);
            return View(categ);
        }

        [HttpPost]
        [Route("[controller]/Busca")]
        public IActionResult Busca(string termo)
        {
            ViewData["termo"] = termo;
            var leiloes = _service.PesquisaLeiloesEmPregaoPorTermo(termo);
            return View(leiloes);
        }
    }
}

src/Alura.LeilaoOnline.WebApp/Controllers/LeilaoApiController.cs
using Microsoft.AspNetCore.Mvc;
using Alura.LeilaoOnline.WebApp.Models;
using Alura.LeilaoOnline.WebApp.Services;

namespace Alura.LeilaoOnline.WebApp.Controllers
{
    [ApiController]
    [Route("/api/leiloes")]
    public class LeilaoApiController : ControllerBase
    {
        IAdminService _service;

        public LeilaoApiController(IAdminService service)
        {
            _service = service;
        }

        [HttpGet]
        public IActionResult EndpointGetLeiloes()
        {
            var leiloes = _service.ConsultaLeiloes();
            return Ok(leiloes);
        }

        [HttpGet("{id}")]
        public IActionResult EndpointGetLeilaoById(int id)
        {
            var leilao = _service.ConsultaLeilaoPorId(id);
            if (leilao == null) return NotFound();
            return Ok(leilao);
        }

        [HttpPost]
        public IActionResult EndpointPostLeilao(Leilao leilao)
        {
            _service.CadastraLeilao(leilao);
            return Ok(leilao);
        }

        [HttpPut]
        public IActionResult EndpointPutLeilao(Leilao leilao)
        {
            if (_service.ConsultaLeilaoPorId(leilao.Id) == null) return NotFound();
            _service.ModificaLeilao(leilao);
            return Ok(leilao);
        }

        [HttpDelete("{id}")]
        public IActionResult EndpointDeleteLeilao(int id)
        {
            var leilao = _service.ConsultaLeilaoPorId(id);
            if (leilao == null) return NotFound();
            _service.RemoveLeilao(leilao);
            return NoContent();
        }

        [HttpPost("{id}/pregao")]
        public IActionResult EndpointIniciaPregao(int id)
        {
            var leilao = _service.ConsultaLeilaoPorId(id);
            if (leilao == null) return NotFound();
            _service.IniciaPregaoDoLeilaoComId(id);
            return Ok();
        }

        [HttpDelete("{id}/pregao")]
        public IActionResult EndpointFinalizaPregao(int id)
        {
            var leilao = _service.ConsultaLeilaoPorId(id);
            if (leilao == null) return NotFound();
            _service.FinalizaPregaoDoLeilaoComId(id);
            return Ok();
        }
    }
}

src/Alura.LeilaoOnline.WebApp/Controllers/LeilaoController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Alura.LeilaoOnline.WebApp.Models;
using Alura.LeilaoOnline.WebApp.Services;

namespace Alura.LeilaoOnline.WebApp.Controllers
{
    public class LeilaoController : Controller
    {
        IAdminService _service;

        public LeilaoController(IAdminService service)
        {
            _service = service;
        }

        public IActionResult Index()
        {
            var leiloes = _service.ConsultaLeiloes();
            return View(leiloes);
        } 

        [HttpGet]
        public IActionResult Insert()
        {
            ViewData["Categorias"] = _service.ConsultaCategorias();
            ViewData["Operacao"] = "Inclusão";
            return View("Form");
        }

        [HttpPost]
        public IActionResult Insert(Leilao model)
        {
            if (ModelState.IsValid)
            {
                _service.CadastraLeilao(model);
                return RedirectToAction("Index");
            }
            ViewData["Categorias"] = _service.ConsultaCategorias();
            ViewData["Operacao"] = "Inclusão";
            return View("Form", model);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewData["Categorias"] = _service.ConsultaCategorias();
            ViewData["Operacao"] = "Edição";
            var leilao = _service.ConsultaLeilaoPorId(id);
            if (leilao == null) return NotFound();
            return View("Form", leilao);
        }

        [HttpPost]
        public IActionResult Edit(Leilao model)
        {
            if (ModelState.IsValid)
            {
                _service.ModificaLeilao(model);
                return RedirectToAction("Index");
            }
            ViewData["Categorias"] = _service.ConsultaCategorias();
            ViewData["Operacao"] = "Edição";
            return View("Form", model);
        }

        [HttpPost]
        public IActionResult Inicia(int id)
        {
            var leilao = _service.ConsultaLeilaoPorId(id);
            if (leilao == null) return NotFound();
            _service.IniciaPregaoDoLeilaoComId(id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Finaliza(int id)
        {
            var leilao = _service.ConsultaLeilaoPorId(id);
            if (leilao == null) return NotFound();
            _service.FinalizaPregaoDoLeilaoComId(id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Remove(int id)
        {
            var leilao = _service.ConsultaLeilaoPorId(id);
            if (leilao == null) return NotFound();
            _service.RemoveLeilao(leilao);
            return NoContent();
        }

        [HttpGet]
        public IActionResult Pesquisa(string termo)
        {
            ViewData["termo"] = termo;
            var leiloes = _service.ConsultaLeiloes()
                .Where(l => string.IsNullOrWhiteSpace(termo) || 
                    l.Titulo.ToUpper().Contains(termo.ToUpper()) || 
                    l.Descricao.ToUpper().Contains(termo.ToUpper()) ||
                    l.Categoria.Descricao.ToUpper().Contains(termo.ToUpper())
                );
            return View("Index", leiloes);
        }
    }
}

src/Alura.LeilaoOnline.WebApp/Views/Home/404.cshtml
@{
    ViewData["Title"] = "Não encontrado!";
}

<div class="jumbotron">
    <h1>Recurso não encontrado!</h1>
    <a class="btn btn-outline-primary" asp-action="Index">Voltar para home</a>
</div>

src/Alura.LeilaoOnline.WebApp/Views/Home/Busca.cshtml
@model IEnumerable<Leilao>

@{
    Layout = "_AreaPublica";
    ViewData["Title"] = "Busca";
}

<h1>Você pesquisou por "@ViewData["termo"]"</h1>
<h3>Leilões encontrados</h3>
<section class="tiles">
    @foreach (var leilao in Model)
    {
        <article class="leilao">
            <span class="image">
                <img src="@leilao.PosterUrl" alt="@leilao.Titulo" />
            </span>
            <h4>@leilao.Titulo</h4>
            <div class="content">
                <p>@leilao.Descricao.Substring(0, 100)</p>
            </div>
        </article>
    }
</section>

src/Alura.LeilaoOnline.WebApp/Views/Home/Categoria.cshtml
@model Categoria

@{
    Layout = "_AreaPublica";
    ViewData["Title"] = "Categoria";
}

<h1>@Model.Descricao</h1>
<span class="image main img-categoria">
    <img src="~/@Model.Imagem" alt="@Model.Descricao" />
</span>
<h3>Leilões em andamento</h3>
<section class="tiles">
@foreach (var leilao in Model.Leiloes.Where(l => l.Situacao == SituacaoLeilao.Pregao))
{
    <article class="leilao">
        <span class="image">
            <img src="@leilao.PosterUrl" alt="@leilao.Titulo" />
        </span>
        <h4>@leilao.Titulo</h4>
        <div class="content">
            <p>@leilao.Descricao.Substring(0,100)</p>
        </div>
    </article>
}
</section>

src/Alura.LeilaoOnline.WebApp/Views/Home/Index.cshtml
@model IEnumerable<CategoriaComInfoLeilao>

@{
    Layout = "_AreaPublica";
    ViewData["Title"] = "Home Page";
}

<header>
    <h1>Bem vindo a Auksjon, seu site de leilões.</h1>
    <p>Etiam quis viverra lorem, in semper lorem. Sed nisl arcu euismod sit amet nisi euismod sed cursus arcu elementum ipsum arcu vivamus quis venenatis orci lorem ipsum et magna feugiat veroeros aliquam. Lorem ipsum dolor sit amet nullam dolore.</p>
</header>
<section class="tiles">
    @foreach (var categ in Model)
    {
        var estilo = $"style{categ.Id}";
        <article class="@estilo">
            <span class="image">
                <img src="@categ.Imagem" alt="@categ.Descricao" />
            </span>
            <a asp-action="Categoria" asp-controller="Home" asp-route-id="@categ.Id" >
                <h2>@categ.Descricao</h2>
                <div class="content">
                    <p>@categ.EmPregao leilões em andamento.</p>
                </div>
            </a>
        </article>
    }
</section>

src/Alura.LeilaoOnline.WebApp/Views/Home/StatusCodeError.cshtml
@model int

@{
    ViewData["Title"] = "Problema encontrado";
}

<div class="jumbotron">
    <h1>Aconteceu o erro @Model!</h1>
    <a class="btn btn-outline-primary" asp-action="Index">Voltar para home</a>
</div>

src/Alura.LeilaoOnline.WebApp/Views/Leilao/Form.cshtml
@model Leilao

@{
    IEnumerable<Categoria> categorias = (IEnumerable<Categoria>)ViewData["Categorias"];
    ViewData["Title"] = $"Leilão - {ViewData["Operacao"]}";
    string operacao = ViewData["Operacao"].ToString();
    bool edicao = operacao == "Edição";
}

<div class="card">
    <div class="card-header">
        <h4>@ViewData["Title"]</h4>
    </div>
    <form class="card-body form-row needs-validation" role="form" asp-controller="Leilao">
        @if (edicao)
        {
            <input type="hidden" asp-for="Id" />
        }
        <div class="form-group col-8">
            <label asp-for="Titulo"></label>
            <input class="form-control" asp-for="Titulo" />
            <span class="invalid-feedback" asp-validation-for="Titulo"></span>
        </div>
        <div class="form-group col-4">
            <label asp-for="IdCategoria">Categoria:</label>
            <select class="form-control" asp-for="IdCategoria">
                @foreach(var categoria in categorias.OrderBy(c => c.Descricao))
                {
                    <option value="@categoria.Id">@categoria.Descricao</option>
                }
            </select>
        </div>
        <div class="form-group col-12">
            <label asp-for="Descricao"></label>
            <textarea class="form-control" asp-for="Descricao" rows="8"></textarea>
        </div>
        <div class="mt-3 text-right bg-secondary">
            <button type="submit" class="btn btn-primary">
                <i class="fa fa-save" aria-hidden="true"></i>
                Gravar
            </button>
            <a class="btn btn-outline-secondary" asp-controller="Leilao" asp-action="Index">Voltar</a>
        </div>
    </form>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

src/Alura.LeilaoOnline.WebApp/Views/Leilao/Index.cshtml
@model IEnumerable<Leilao>

@{
    ViewData["Title"] = "Leilões";
    var termo = ViewData["termo"];
}

<div class="card">
    <div class="card-header d-flex">
        <h4 class="flex-grow-1">Leilões</h4>
        <a class="btn btn-outline-primary" asp-controller="Leilao" asp-action="Insert" title="Inclusão">
            <i class="fa fa-plus" aria-hidden="true"></i>
            Novo
        </a>
    </div>
    <div class="card-body">
        <form class="form-inline mb-3" asp-controller="Leilao" asp-action="Pesquisa" method="get">
            <input name="termo" class="form-control flex-grow-1"
                    value="@termo"
                    placeholder="Pesquisar por título, categoria ou descrição..." />
            <button class="btn btn-outline-secondary ml-2">
                <i class="fa fa-search"></i>
                <span class="d-none d-md-inline">Pesquisar</span>
            </button>
        </form>
        <div class="row">
            <div class="col-12">
                <table class="col-12 table table-striped">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Título</th>
                            <th>Situação</th>
                            <th>Descrição</th>
                            <th>Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach(var leilao in Model)
                        {
                            <tr class="row-leilao-@leilao.Id">
                                <td>@leilao.Id</td>
                                <td>@leilao.Titulo</td>
                                <td>
                                    @switch (leilao.Situacao)
                                    {
                                        case SituacaoLeilao.Rascunho:
                                            <span>Rascunho</span>
                                            break;
                                        case SituacaoLeilao.Pregao:
                                            <span>Pregão iniciado em @leilao.Inicio.Value.ToString("dd/MM/yyyy hh:mm")</span>
                                            break;
                                        case SituacaoLeilao.Finalizado:
                                            <span>Finalizado em @leilao.Termino.Value.ToString("dd/MM/yyyy hh:mm")</span>
                                            break;
                                        default:
                                            <span>@leilao.Situacao</span>
                                            break;
                                    }
                                </td>
                                <td>@leilao.Descricao</td>
                                <td>
                                    @if (leilao.Situacao == SituacaoLeilao.Rascunho)
                                    {
                                        <a class="btn btn-light" asp-controller="Leilao" asp-action="Edit" asp-route-id="@leilao.Id" title="Edição">
                                            <i class="fa fa-pencil-alt" aria-hidden="true"></i>
                                        </a>
                                        <form asp-action="Inicia">
                                            <input type="hidden" name="id" value="@leilao.Id" />
                                            <button class="btn btn-light" title="Iniciar Pregão">
                                                <i class="fas fa-play-circle"></i>
                                            </button>
                                        </form>
                                    }
                                    @if (leilao.Situacao != SituacaoLeilao.Pregao)
                                    {
                                        <a class="btn btn-light btnRemoveLeilao" data-id="@leilao.Id" data-titulo="@leilao.Titulo" title="Exclusão">
                                            <i class="fa fa-trash" aria-hidden="true"></i>
                                        </a>
                                    }
                                    @if (leilao.Situacao == SituacaoLeilao.Pregao)
                                    {
                                        <form asp-action="Finaliza">
                                            <input type="hidden" name="id" value="@leilao.Id" />
                                            <button class="btn btn-light" title="Finalizar Pregão">
                                                <i class="fas fa-stop-circle"></i>
                                            </button>
                                        </form>
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

src/Alura.LeilaoOnline.WebApp/Views/Shared/_AreaPublica.cshtml
<!DOCTYPE HTML>
<!--
    Phantom by HTML5 UP
    html5up.net
    Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
<head>
    <title>Auksjon - Leilão de Ofertas</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="~/assets/css/main.css" />
    <noscript><link rel="stylesheet" href="~/assets/css/noscript.css" /></noscript>
</head>
<body class="is-preload">
    <!-- Wrapper -->
    <div id="wrapper">

        <!-- Header -->
        <header id="header">
            <div class="inner">

                <!-- Logo -->
                <a asp-action="Index" class="logo">
                    <span class="symbol"><img src="~/images/logo.svg" alt="" /></span><span class="title">Auksjon</span>
                </a>

                <!-- Nav -->
                <nav>
                    <ul>
                        <li><a href="#menu">Menu</a></li>
                    </ul>
                </nav>

            </div>
        </header>

        <!-- Menu -->
        <nav id="menu">
            <h2>Menu</h2>
            <ul>
                <li><a asp-action="Index">Home</a></li>
                <li><a asp-action="Login">Login</a></li>
                <li>
                    <form asp-action="Busca">
                        <input type="text" name="termo" placeholder="Pesquise um leilão..." autocomplete="off" required />
                    </form>
                </li>
            </ul>
        </nav>

        <!-- Main -->
        <div id="main">
            <div class="inner">
                @RenderBody()
            </div>
        </div>

        <!-- Footer -->
        <footer id="footer">
            <div class="inner">
                <section>
                    <h2>Contato</h2>
                    <form method="post" action="#">
                        <div class="fields">
                            <div class="field half">
                                <input type="text" name="name" id="name" placeholder="Nome" />
                            </div>
                            <div class="field half">
                                <input type="email" name="email" id="email" placeholder="Email" />
                            </div>
                            <div class="field">
                                <textarea name="message" id="message" placeholder="Mensagem"></textarea>
                            </div>
                        </div>
                        <ul class="actions">
                            <li><input type="submit" value="Enviar" class="primary" /></li>
                        </ul>
                    </form>
                </section>
                <section>
                    <h2>Redes Sociais</h2>
                    <ul class="icons">
                        <li><a href="#" class="icon brands style2 fa-facebook-f"><span class="label">Facebook</span></a></li>
                        <li><a href="#" class="icon brands style2 fa-instagram"><span class="label">Instagram</span></a></li>
                        <li><a href="#" class="icon brands style2 fa-github"><span class="label">GitHub</span></a></li>
                        <li><a href="#" class="icon solid style2 fa-phone"><span class="label">Phone</span></a></li>
                        <li><a href="#" class="icon solid style2 fa-envelope"><span class="label">Email</span></a></li>
                    </ul>
                </section>
                <ul class="copyright">
                    <li>&copy; 2020 Auksjon. Leilão online de ofertas</li>
                    <li>Template: <a target="_blank" href="http://html5up.net/phantom">Phantom - HTML5UP</a></li>
                    <li>Imagens: <a target="_blank" href="http://picsum.photos">Picsum</a> e <a target="_blank" href="http://unsplash.com">Unsplash</a> </li>
                </ul>
            </div>
        </footer>

    </div>

    <!-- Scripts -->
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/js/browser.min.js"></script>
    <script src="assets/js/breakpoints.min.js"></script>
    <script src="assets/js/util.js"></script>
    <script src="assets/js/main.js"></script>

</body>
</html>

src/Alura.LeilaoOnline.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Alura.LeilaoOnline</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/dist/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="bg-secondary">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Área Pública</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Leilao" asp-action="Index">Administração</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-white text-center">
        <div class="container">
            SOLID &copy; 2020 - Daniel Portugal
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>